version: "3.9"
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/coscon
      - PORT=3002
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

